### ISSUE TITLE
Exception at launch of program

### ISSUE THREAD

**Issue by Ariwenie** [coldino/Larkator#23]
I have to post screenshot because i can not copy anything from MsgBox.

![Screenshot](https://user-images.githubusercontent.com/45144039/48672858-89a9bb00-eb3b-11e8-9b9d-a6fd381a16b2.png)

This is happen immediately at launch of program and occuring for last several days after update.

**Comment by VIOrealm** [comment]
It looks like an error with the User.config file.  I think I remember that it will recreate itself.  Rename it and relaunch.  If that doesn't work, uninstall and reinstall.  I'm not the developer but have been messing around with it for a while.

**Comment by coldino** [comment]
I can only read some of it due to the language. It does indeed look like some issue with the user config file.

First step - find the `user.config` file mentioned in the first long line of the error message and either rename it out of the way, or have a look inside it and see what's wrong at line 14 if you are comfortable in a text editor.

The full error in English would be useful. Ctrl-C should copy the text of the message box to your clipboard so you can paste it into a comment.
