### ISSUE TITLE
Automatically re-reads your save file when it changes not working

### ISSUE THREAD

**Issue by b-morgan** [coldino/Larkator#28]
I have a scheduled task that copies the latest saved game from my Nitrado server and updates the save file (located in a Google Drive folder) that Larkator is pointed at. The server is set to save every 15 minutes and my scheduled task runs every 30 minutes. Larkator doesn't update when the file changes.

As an enhancement, could Larkator put a time in the status line when it reads (and updates) the save file, something like "ARK processing completed at hh:mm:ss". A control (button?) to force it to re-read the save file might be useful as well.

**Comment by maxlomb** [comment]
Hello,

jsut a question. I was using always the LARKATOR tool in Single Player. Now I started playing PVE. I play on an official server, NITRADO (EU-430-on-Nitrado). Is it possible, even if you are not admin, to get somehow the saved game from the Nitrado server and for example find out where are high levels wild dinos?
Thank you

**Comment by coldino** [comment]
@maxlomb No. You can only use Larkator if you own the server or otherwise have access to the save file.

@b-morgan This is because Larkator only listens for the **rename** file-change event, to avoid repeated triggers from the normal Ark save process. You could easily support this in your scheduled script:
 1) Download to a temporary filename
 2) Delete the old ark
 3) Rename your new ark to the correct filename

I'll also look to see if I can safely extend file monitoring to include in-place changes.

**Comment by coldino** [comment]
Closing, assuming this change works for you.

**Comment by b-morgan** [comment]
Yes, it is working very well! Thank you!
