### ISSUE TITLE
LostIsland Support?

### ISSUE THREAD

**Issue by CrazyOlli** [coldino/Larkator#62]
Hi there, will be support for LostIsland importet? I used your tool for a LostIsland Server, but all coordinates are outside the real positions on Server.

Thx :)

**Comment by coldino** [comment]
Yes, LostIsland support is coming. I've done the map calibration work, but there are two problems:
 * The Lost Island map is **really** far off in terms of visuals vs coordinates. Fixing this means it won't match the in-gane map position, so I need to experiment and figure out what works best.
 * Visual Studio, the development tool needed to work on Larkator has stopped working on my machine after a series of bluscreens. I've fixed the bluscreens (expensively 😂) but still need to work out how to get VS working again.

**Comment by CrazyOlli** [comment]
Thanks a lot, that sounds great. The ingame Map also did not match exactly, maybe its a general problem?

**Comment by coldino** [comment]
Yes it's very much a problem with the map graphic WC made. The grid position doesn't match what the in-game GPS says, by quite a long way. This is common, but it is extreme on this map.

**Comment by jmbjorndalen** [comment]
It looks like this might belong here as extra information about the map support and coordinates. 

I'm trying out Larkator 1.12.0.0 with Lost Island now. It looks like the visual / map locations of dinos are roughly correct, but the reported coordinates (in "The Chase" or if you hover over a circle) look like they are computed as if it was on Crystal Isles instead of Lost Island. I verified this by checking the location of 4 Griffins dumped using ark-tools. The coordinates that Larkator reports for the same creatures match the Crystal Isles transformations: 

- lat = y / 16000 + 48.75
- lon = x / 17000 + 50

Lost Island uses these transformations (https://ark.fandom.com/wiki/Coordinates): 

- lat = y / 15300 + 51.634
- lon = x / 15300 + 49.02

Thanks for a nice tool. Now I just have to figure out if I can compile it on Linux ;-)

**Comment by coldino** [comment]
Thanks for the report, or the reminder I should say. Yup, the coordinates were correct for how the map was at release but WC have since changed them significantly. I plan to update soon.

I know about the transforms on the wiki - my other project Purlovia is where the wiki actually gets this data from 😂 These cover the conversion from XYZ to Lat/Lon but do not handle the position and scale on the handheld map image, which is usually the bigger problem.

As for the Linux side, you'll probably need to use WINE as WPF isn't supported on the Linux native versions of .Net at all, I believe. Any issues, start another thread please.

**Comment by coldino** [comment]
With today's update Lost Island should be well calibrated once again.
