### ISSUE TITLE
Stats dump?

### ISSUE THREAD

**Issue by esalkin1** [coldino/Larkator#63]
Is there any way to dump the dino counts to a CSV fille?  For instance:
Dodo,1203
Rex ,324
Raptor,821
Castoroides,8
Alpha T-Rex,0

This would really help admins tweak the numbers on their servers or use the command line to add a missing one.

**Comment by coldino** [comment]
This looked like a useful thing to me, but not a good fit for inside Larkator itself because it would better on the server. So, I made a quick command-line tool to do it and added it to the project.

You can see the code in 0528a16f75f44c4777898f8c04e782e8aefd1e75, or grab the built version here: [SpeciesCount.zip](https://github.com/coldino/Larkator/files/7901416/SpeciesCount.zip).
*It requires .Net Core 6 but should run on pretty much all platforms.*

Example:
```sh
> SpeciesCount.exe --wild LostIsland.ark
Species,Count
Coel_Character_BP_C, 4936
Dragonfly_Character_BP_C, 2323
Coel_Character_BP_Ocean_C, 1947
Dodo_Character_BP_C, 1489
Ant_Character_BP_C, 1476
Dilo_Character_BP_C, 1422
Compy_Character_BP_C, 1142
...
```

Let me know if it's useful!

**Comment by esalkin1** [comment]
Coldino,

Works like a charm!  Not being a programmer, it would have taken me a few hundred hours to figure that out.  Thanks to you I can better spend those hours getting eaten by dinos!

Thanks again;
[J0241043]
Ed Niklas<https://www.linkedin.com/in/edniklas?trk=profile-badge>
Home:  (813) 877-7067
Cell:       (813) 999-0234
Public:    ***@***.******@***.***>
Private:  ***@***.******@***.***> (not for publication or commercial use.)
Web:      http://www.linkedin.com/in/edniklas
